// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package querier

import (
	"time"

	"github.com/google/uuid"
)

type DailyAggregate struct {
	ID               uuid.UUID `json:"id"`
	ValidatorAddress string    `json:"validator_address"`
	DelegatorAddress string    `json:"delegator_address"`
	Date             time.Time `json:"date"`
	TotalAmount      int64     `json:"total_amount"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type DelegationSnapshot struct {
	ID               uuid.UUID `json:"id"`
	ValidatorAddress string    `json:"validator_address"`
	DelegatorAddress string    `json:"delegator_address"`
	AmountUatom      int64     `json:"amount_uatom"`
	ChangeUatom      int64     `json:"change_uatom"`
	Timestamp        time.Time `json:"timestamp"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}
