// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package querier

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDailyAggregate(ctx context.Context, arg CreateDailyAggregateParams) (uuid.UUID, error)
	CreateDelegationSnapshot(ctx context.Context, arg CreateDelegationSnapshotParams) (uuid.UUID, error)
	GetCountDailyAggregateByValidator(ctx context.Context, validatorAddress string) (int64, error)
	GetCountDelegationSnapshotByValidator(ctx context.Context, validatorAddress string) (int64, error)
	GetCountDelegatorHistoryByValidator(ctx context.Context, arg GetCountDelegatorHistoryByValidatorParams) (int64, error)
	GetDailyAggregateByValidator(ctx context.Context, arg GetDailyAggregateByValidatorParams) ([]GetDailyAggregateByValidatorRow, error)
	GetDelegationSnapshotByValidator(ctx context.Context, arg GetDelegationSnapshotByValidatorParams) ([]GetDelegationSnapshotByValidatorRow, error)
	GetDelegationSnapshotByValidatorAndDelegator(ctx context.Context, arg GetDelegationSnapshotByValidatorAndDelegatorParams) (GetDelegationSnapshotByValidatorAndDelegatorRow, error)
	GetDelegatorHistoryByValidator(ctx context.Context, arg GetDelegatorHistoryByValidatorParams) ([]GetDelegatorHistoryByValidatorRow, error)
	GetLatestDelegationSnapshot(ctx context.Context) ([]GetLatestDelegationSnapshotRow, error)
}

var _ Querier = (*Queries)(nil)
