// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/scheduler/validator/daily": {
            "post": {
                "description": "Scheduler For Daily Collect Validator Data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "Scheduler For Daily Collect Validator Data",
                "operationId": "schedulerForDailyCollectValidatorData",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResp200"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp401"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp404"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp500"
                        }
                    }
                }
            }
        },
        "/api/v1/scheduler/validator/hourly": {
            "post": {
                "description": "Scheduler For Hourly Collect Validator Data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "Scheduler For Hourly Collect Validator Data",
                "operationId": "schedulerForHourlyCollectValidatorData",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResp200"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp401"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp404"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp500"
                        }
                    }
                }
            }
        },
        "/api/v1/validators/{validatorAddress}/delegations/daily": {
            "get": {
                "description": "Get Daily Delegation Snapshot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "Get Daily Delegation Snapshot",
                "operationId": "getDailyDelegationSnapshot",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.SuccessResp200"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.PaginationResp-dto_GetDailySnapshotResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp401"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp404"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp500"
                        }
                    }
                }
            }
        },
        "/api/v1/validators/{validatorAddress}/delegations/hourly": {
            "get": {
                "description": "Get Hourly Delegation Snapshot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "Get Hourly Delegation Snapshot",
                "operationId": "getHourlyDelegationSnapshot",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.SuccessResp200"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.PaginationResp-dto_GetHourlySnapshotResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp401"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp404"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp500"
                        }
                    }
                }
            }
        },
        "/api/v1/validators/{validatorAddress}/delegator/{delegatorAddress}/history": {
            "get": {
                "description": "Get Delegator History",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "Get Delegator History",
                "operationId": "getDelegatorHistory",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.SuccessResp200"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.PaginationResp-dto_GetDelegatorHistoryResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp401"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp404"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.FailedResp500"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ErrorMsgResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.FailedResp400": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ErrorMsgResp"
                    }
                },
                "statusCode": {
                    "type": "integer",
                    "default": 400
                },
                "success": {
                    "type": "boolean",
                    "default": false
                }
            }
        },
        "dto.FailedResp401": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ErrorMsgResp"
                    }
                },
                "statusCode": {
                    "type": "integer",
                    "default": 401
                },
                "success": {
                    "type": "boolean",
                    "default": false
                }
            }
        },
        "dto.FailedResp404": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ErrorMsgResp"
                    }
                },
                "statusCode": {
                    "type": "integer",
                    "default": 404
                },
                "success": {
                    "type": "boolean",
                    "default": false
                }
            }
        },
        "dto.FailedResp500": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ErrorMsgResp"
                    }
                },
                "statusCode": {
                    "type": "integer",
                    "default": 500
                },
                "success": {
                    "type": "boolean",
                    "default": false
                }
            }
        },
        "dto.GetDailySnapshotResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.GetDelegatorHistoryResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "change": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "dto.GetHourlySnapshotResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "amount": {
                    "type": "integer"
                },
                "change": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "dto.Next": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                }
            }
        },
        "dto.PaginationResp-dto_GetDailySnapshotResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GetDailySnapshotResponse"
                    }
                },
                "isLoadMore": {
                    "type": "boolean"
                },
                "next": {
                    "$ref": "#/definitions/dto.Next"
                },
                "prev": {
                    "$ref": "#/definitions/dto.Prev"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.PaginationResp-dto_GetDelegatorHistoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GetDelegatorHistoryResponse"
                    }
                },
                "isLoadMore": {
                    "type": "boolean"
                },
                "next": {
                    "$ref": "#/definitions/dto.Next"
                },
                "prev": {
                    "$ref": "#/definitions/dto.Prev"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.PaginationResp-dto_GetHourlySnapshotResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GetHourlySnapshotResponse"
                    }
                },
                "isLoadMore": {
                    "type": "boolean"
                },
                "next": {
                    "$ref": "#/definitions/dto.Next"
                },
                "prev": {
                    "$ref": "#/definitions/dto.Prev"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.Prev": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                }
            }
        },
        "dto.SuccessResp200": {
            "type": "object",
            "properties": {
                "data": {},
                "statusCode": {
                    "type": "integer",
                    "default": 200
                },
                "success": {
                    "type": "boolean",
                    "default": true
                }
            }
        }
    },
    "securityDefinitions": {
        "authorization": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Validator Tracking Service API",
	Description:      "API Spec for Validator Tracking Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
